import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/chat.dart';
import '../models/chat_message.dart';

class ChatService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Get chats for current user
  Stream<List<ChatModel>> getUserChats(String userId) {
    return _firestore
        .collection('chats')
        .where('participantIds', arrayContains: userId)
        .orderBy('updatedAt', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) => ChatModel.fromMap(doc.data(), doc.id))
              .where((chat) => !chat.archivedBy.contains(userId))
              .toList();
        });
  }

  /// Get active (non-closed) chats for badge indicator
  Stream<List<ChatModel>> getActiveChats(String userId) {
    return _firestore
        .collection('chats')
        .where('participantIds', arrayContains: userId)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) => ChatModel.fromMap(doc.data(), doc.id))
              .where((chat) => !chat.isClosed && !chat.archivedBy.contains(userId))
              .toList();
        });
  }

  /// Get messages for a specific chat
  Stream<List<ChatMessage>> getChatMessages(String chatId) {
    return _firestore
        .collection('chats')
        .doc(chatId)
        .collection('messages')
        .orderBy('sentAt', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) => ChatMessage.fromMap(doc.data(), doc.id))
              .toList();
        });
  }

  /// Send a message
  Future<void> sendMessage(String chatId, String senderId, String text) async {
    try {
      final now = DateTime.now();

      final message = ChatMessage(
        id: '', // Generated by Firestore
        senderId: senderId,
        text: text,
        sentAt: now,
      );

      // Add to messages subcollection
      await _firestore
          .collection('chats')
          .doc(chatId)
          .collection('messages')
          .add(message.toMap());

      // Update chat lastMessage, updatedAt, and mark as seen for the sender
      await _firestore.collection('chats').doc(chatId).update({
        'lastMessage': text,
        'updatedAt': now,
        'lastSeenAt.$senderId': now,
      });
    } catch (e) {
      rethrow;
    }
  }

  /// Fetch a user's student ID from their Firestore profile
  Future<String> getStudentId(String uid) async {
    try {
      final doc = await _firestore.collection('Users').doc(uid).get();
      final studentId = doc.data()?['studentID'] as String?;
      if (studentId != null && studentId.isNotEmpty) return studentId;
      // Fallback: extract from stored email field
      final email = doc.data()?['email'] as String?;
      if (email != null) return email.split('@').first;
    } catch (_) {}
    return uid; // last resort
  }


  /// Watch a single chat document for real-time updates (e.g. isClosed changes)
  Stream<ChatModel> watchChat(String chatId) {
    return _firestore
        .collection('chats')
        .doc(chatId)
        .snapshots()
        .map((doc) => ChatModel.fromMap(doc.data() ?? {}, doc.id));
  }

  /// Close a chat — marks it as closed so both users see the closed state
  Future<void> closeChat(String chatId, String closedByStudentId) async {
    try {
      await _firestore.collection('chats').doc(chatId).update({
        'isClosed': true,
        'closedByStudentId': closedByStudentId,
      });
    } catch (e) {
      rethrow;
    }
  }

  /// Get archived chats for current user
  Stream<List<ChatModel>> getArchivedChats(String userId) {
    return _firestore
        .collection('chats')
        .where('participantIds', arrayContains: userId)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) => ChatModel.fromMap(doc.data(), doc.id))
              .where((chat) => chat.archivedBy.contains(userId))
              .toList();
        });
  }

  /// Archive a chat for a specific user
  Future<void> archiveChat(String chatId, String userId) async {
    try {
      await _firestore.collection('chats').doc(chatId).update({
        'archivedBy': FieldValue.arrayUnion([userId]),
      });
    } catch (e) {
      rethrow;
    }
  }

  /// Unarchive a chat for a specific user
  Future<void> unarchiveChat(String chatId, String userId) async {
    try {
      await _firestore.collection('chats').doc(chatId).update({
        'archivedBy': FieldValue.arrayRemove([userId]),
      });
    } catch (e) {
      rethrow;
    }
  }

  /// Mark a specific chat as seen/read for the given user
  Future<void> markChatAsSeen(String chatId, String userId) async {
    try {
      await _firestore.collection('chats').doc(chatId).update({
        'lastSeenAt.$userId': DateTime.now(),
      });
    } catch (_) {
      // Non-critical — silently ignore
    }
  }

  /// Close all active chats for a user (used during blocking)
  Future<void> closeAllUserChats(String userId, String closedByStudentId) async {
    try {
      final query = await _firestore
          .collection('chats')
          .where('participantIds', arrayContains: userId)
          .where('isClosed', isEqualTo: false)
          .get();

      final batch = _firestore.batch();
      for (var doc in query.docs) {
        batch.update(doc.reference, {
          'isClosed': true,
          'closedByStudentId': closedByStudentId,
        });
      }
      await batch.commit();
    } catch (e) {
      rethrow;
    }
  }
}
