// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc8a4UaajVAf6qXSNmEy14L6BzVlm-Lc8',
    appId: '1:681593766408:web:4f121008a698c6048147bd',
    messagingSenderId: '681593766408',
    projectId: 'mbyb-4e6c8',
    authDomain: 'mbyb-4e6c8.firebaseapp.com',
    storageBucket: 'mbyb-4e6c8.firebasestorage.app',
    measurementId: 'G-PMCJZPC1FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rnPt42w1ggl3tiuye8mJrK6mUktIw0o',
    appId: '1:681593766408:android:630f48030154f2ec8147bd',
    messagingSenderId: '681593766408',
    projectId: 'mbyb-4e6c8',
    storageBucket: 'mbyb-4e6c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfrMriSKLHHa7cHIFxgPzWoLcA0haLJjY',
    appId: '1:681593766408:ios:c7d5271b3c92c4448147bd',
    messagingSenderId: '681593766408',
    projectId: 'mbyb-4e6c8',
    storageBucket: 'mbyb-4e6c8.firebasestorage.app',
    iosBundleId: 'com.example.mbyb',
  );
}
